using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.IO;
using System.Text;
using System.Text.Json;

namespace BetterPrompt.ViewModels;

public partial class NewProjectViewModel : ObservableObject
{
    [ObservableProperty] private string _projectName = string.Empty;
    [ObservableProperty] private string _description = string.Empty;
    [ObservableProperty] private string _goal = string.Empty;
    [ObservableProperty] private string _targetAudience = string.Empty;
    [ObservableProperty] private string _platform = "Windows Desktop";
    [ObservableProperty] private string _language = string.Empty;
    [ObservableProperty] private string _database = string.Empty;
    [ObservableProperty] private string _coreFeatures = string.Empty;
    [ObservableProperty] private string _outOfScope = string.Empty;
    [ObservableProperty] private string _nonFunctionalRequirements = string.Empty;
    [ObservableProperty] private string _timeline = string.Empty;
    [ObservableProperty] private string _similarApps = string.Empty;
    [ObservableProperty] private string _projectPath = string.Empty;
    [ObservableProperty] private string _generateStatus = string.Empty;
    [ObservableProperty] private bool _generateSuccess;
    [ObservableProperty] private bool _hasGenerateStatus;

    public static readonly List<string> PlatformOptions =
    [
        "Windows Desktop",
        "Web App",
        "Mobile App",
        "Cross-platform Desktop",
        "CLI Tool",
        "REST API / Backend",
        "Library / Package",
    ];

    [RelayCommand]
    private void BrowseProjectPath()
    {
        var dialog = new Microsoft.Win32.OpenFolderDialog { Title = "Select Project Folder" };
        if (dialog.ShowDialog() == true)
            ProjectPath = dialog.FolderName;
    }

    [RelayCommand]
    private void GenerateProject()
    {
        HasGenerateStatus = true;

        if (string.IsNullOrWhiteSpace(ProjectName))
        {
            GenerateStatus = "Project name is required.";
            GenerateSuccess = false;
            return;
        }
        if (string.IsNullOrWhiteSpace(ProjectPath))
        {
            GenerateStatus = "Project directory is required.";
            GenerateSuccess = false;
            return;
        }

        try
        {
            Directory.CreateDirectory(ProjectPath);
            File.WriteAllText(Path.Combine(ProjectPath, "CLAUDE.md"), BuildClaudeMd());
            File.WriteAllText(Path.Combine(ProjectPath, "project-scope.json"), BuildScopeJson());
            GenerateSuccess = true;
            GenerateStatus = $"Created CLAUDE.md and project-scope.json in {ProjectPath}";
        }
        catch (Exception ex)
        {
            GenerateSuccess = false;
            GenerateStatus = $"Error: {ex.Message}";
        }
    }

    [RelayCommand]
    private void OpenProjectFolder()
    {
        if (Directory.Exists(ProjectPath))
            System.Diagnostics.Process.Start(
                new System.Diagnostics.ProcessStartInfo(ProjectPath) { UseShellExecute = true });
    }

    private string BuildClaudeMd()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {ProjectName}");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(Description))
        {
            sb.AppendLine($"> {Description}");
            sb.AppendLine();
        }

        AppendSection(sb, "Goal", Goal);
        AppendSection(sb, "Target Audience", TargetAudience);

        sb.AppendLine("## Technical Stack");
        sb.AppendLine($"- **Platform:** {Platform}");
        if (!string.IsNullOrWhiteSpace(Language))
            sb.AppendLine($"- **Language / Framework:** {Language}");
        if (!string.IsNullOrWhiteSpace(Database))
            sb.AppendLine($"- **Database / Storage:** {Database}");
        sb.AppendLine();

        AppendBulletSection(sb, "Core Features", CoreFeatures);
        AppendBulletSection(sb, "Out of Scope", OutOfScope);
        AppendSection(sb, "Non-Functional Requirements", NonFunctionalRequirements);
        AppendSection(sb, "Timeline", Timeline);
        AppendSection(sb, "Reference / Inspiration", SimilarApps);

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by BetterPrompt on {DateTime.Now:yyyy-MM-dd}*");
        return sb.ToString();
    }

    private static void AppendSection(StringBuilder sb, string heading, string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return;
        sb.AppendLine($"## {heading}");
        sb.AppendLine(value.Trim());
        sb.AppendLine();
    }

    private static void AppendBulletSection(StringBuilder sb, string heading, string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return;
        sb.AppendLine($"## {heading}");
        foreach (var line in value.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var item = line.Trim().TrimStart('-').Trim();
            if (!string.IsNullOrWhiteSpace(item))
                sb.AppendLine($"- {item}");
        }
        sb.AppendLine();
    }

    private string BuildScopeJson()
    {
        static string[] ToList(string raw) =>
            raw.Split('\n', StringSplitOptions.RemoveEmptyEntries)
               .Select(l => l.Trim().TrimStart('-').Trim())
               .Where(l => !string.IsNullOrWhiteSpace(l))
               .ToArray();

        var scope = new
        {
            projectName = ProjectName,
            description = Description,
            goal = Goal,
            targetAudience = TargetAudience,
            technical = new { platform = Platform, language = Language, database = Database },
            coreFeatures = ToList(CoreFeatures),
            outOfScope = ToList(OutOfScope),
            nonFunctionalRequirements = NonFunctionalRequirements,
            timeline = Timeline,
            similarApps = SimilarApps,
            generatedAt = DateTime.Now.ToString("yyyy-MM-dd"),
        };

        return JsonSerializer.Serialize(scope, new JsonSerializerOptions { WriteIndented = true });
    }
}
